[project]
name = "crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymongo>=4.6.0",
    "python-dotenv>=1.0.0"
    "beautifulsoup4>=4.14.2",
    "requests>=2.32.5",
]
