[project]
name = "scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "bson>=0.5.10",
    "python-dotenv>=1.0.0",
    "pymongo>=4.6.0",
    "boto3>=1.28.0",
    "requests>=2.32.5",
]
